repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        name: Checking YAML
    -   id: trailing-whitespace
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/jonasbn/pre-commit-hooks
    rev: v0.6.0
    hooks:
    -   id: spellcheck
