matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - 'blockquote > p'
    - code
    - pre
    - 'html > body > p'
  sources:
  - '!_site/*.md|*/*.md'
  ##- 'go/reading_benchmark_results.md'
  default_encoding: utf-8
