language: node_js
node_js:
- '8'
install:
- npm install -g markdownlint-cli
script:
- markdownlint *.md ; markdownlint */*.md
notifications:
  slack:
    secure: e03EB9eKpAFr/lL3SWnS5yakB4hiTf3DA39mFpeaczM+qDx1phsyWtYWDwD0ZLrHrYBOTmrjvpg2KLs5ewvzmxtK3C99wYBh05bmpbyolnqVWfE7ONFf+iZxf8LUcjfcpsXvn8zpWBieLIT7bM6IGogT9wxXITCAmgkNUfP63Uzzm1Au92g4MLEllgNlozN9qvv67VzXYVWD36ItLRnwI0EPxeHeFwFvqB5ocFq9BxE6auSZBpzaRRmJPImAaEOovel0aTxVtur+dGefGQ3obZGkUq+ZRXRlh8JS6xkOVuDkFx3LtMGSTtxiZPWzUIjv9Xsu3qfWcZzG6VEpS/O0uRUjWDKgHlkBCZ+Ve1ciYSaEu8neHOk5Pj1/8ftpZYm2kZHShJtR8i0FMVDuOlWhiMe7+w9Wwv2FBuxhDU4EYwi2RstqTQdBZtv5uP3lpVm9BAD94ESQY5aHGAbvz/1oYSY7Qck9khFZwxmNXtbM27NM2ZvJ3p7vXHBBwd+y8ABju6Vt3jpNxEv/OX8oYgQ9nw7evimvIhAvAu5DLXXm6bvsseAJioXJsKFtr/hbE578y+Y/SYliPvCmCVKRIf3O3fG08KLiYHXCvyZYk3F+hBVCy1VifjMKHOkW4DTvYwlCoSXc0m9zWipN5yHieYmoqfVUSi/iT3tXV8M/AfL2Yic=
